Minor Tweaks.

diff --git a/newall b/newall
--- a/newall
+++ b/newall
@@ -1,11 +1,12 @@
 #!/bin/bash
 
 if [[ $EUID -ne 0 ]]; then
-	echo "This script must be run as root."
+	echo "newall: This script must be run as root."
 	exit 1
 fi
 if [ ! -f $1 ]; then
-    echo "File $1 not found!"
+    echo "newall: File $1 not found!"
+    exit 1
 else
 	cp $1 /usr/share/backgrounds
 	mv /usr/share/backgrounds/$1 /usr/share/backgrounds/warty-final-ubuntu.png
